apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: basic-replica-set
  labels:
    created-by: robotmaker76
    app: learn-the-kube
spec:
  replicas: 4
  selector:
    matchLabels:
      app: learn-the-kube
  template:
    metadata:
      labels:
        app: learn-the-kube
    spec:
      containers:
      - name: k8s-basic
        image: jerepondumie/k8s-basic