apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: basic-replica-set
  labels:
    created-by: robotmaker76
    app: learn-the-kube
spec:
  replicas: 4
  selector:
    matchLabels:
      app: learn-the-kube
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
           - key: kubernetes.io/hostname
             operator: In
             values:
             - kube-slave-1
             - kube-slave-2
  containers:
  - name: k8s-basic
    image: jerepondumie/k8s-basic
