apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
  labels:
    created-by: robotmaker76
    app: learn-the-kube
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
           - key: kubernetes.io/hostname
             operator: In
             values:
             -  kube-slave-1
  containers:
  - name: k8s-basic
    image: jerepondumie/k8s-basic
